apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.28
          ports:
            - containerPort: 80

        - name: multitool
          image: praqma/network-multitool:alpine-extra
          ports:
            - containerPort: 8080
          env:
          - name: HTTP_PORT
            value: "8080"
          ports:
          - containerPort: 8080
            name: http-port