---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            mode: 0755
          with_items: "{{ clickhouse_packages }}"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm
          - clickhouse-client-{{ clickhouse_version }}.x86_64.rpm
          - clickhouse-server-{{ clickhouse_version }}.x86_64.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
- name: Install Vector
  hosts: vector
  tasks:
    - name: Download Vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.27.0/vector-0.27.0-1.x86_64.rpm"
        dest: "./vector-0.27.0-1.x86_64.rpm"
    - name: Install Vector
      become: true
      ansible.builtin.yum:
        name: "vector-0.27.0-1.x86_64.rpm"
- name: Install lighthouse
  hosts: lighthouse
  become: true
  tasks:
    - name: install EPEL repo
      become: yes
      yum: name=epel-release state=present
    - name: Install nginx
      ansible.builtin.yum:
        name: "nginx"
        state: "latest"
        update_cache: true
    - name: start-nginx
      service:
        name: nginx
        state: started
    - name: nginx. create config
      template:
        src: default.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
    - name: Install git
      ansible.builtin.yum:
        name: "git"
        state: "release-0.22"
        update_cache: true
    - name: Lighthouse
      git:
        repo: https://github.com/VKCOM/lighthouse.git
        dest: /home/repos/
        clone: yes
        update: yes