apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-app
  template:
    metadata:
      labels:
        app: data-exchange-app
    spec:
      containers:

        - name: busybox-container
          image: busybox
          command: ['sh', '-c', 'while true; do echo $(date) >> /shared-data/data.txt; sleep 5; done']
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-data

        - name: network-multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-data
      volumes:
        - name: shared-volume
          emptyDir: {}
