apiVersion: v1
kind: Service
metadata:
  name: my-app-service-ext
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: nginx-port
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool-port
      port: 9002
      targetPort: 8080
      nodePort: 30002
