{
 "title": "My_first_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{job=\"prometheus\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemFree %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {fstype=~\"ext4|xfs\"} / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|xfs\"} / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"prometheus\",mountpoint=\"/\"} / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}